### ISSUE TITLE
Trace missing DD_API_KEY

### ISSUE THREAD

**Issue by Whitespace** [DataDog/heroku-buildpack-datadog#1]
If you install this and `heroku run cat /tmp/logs/datadog/trace-agent.log -a my-app` you'll see that it's missing `DD_API_KEY`.

The workaround is to just `heroku config:set DD_API_KEY=...` but there might be a better way.

**Comment by talwai** [comment]
Thanks @Whitespace , yea that's correct - we renamed the env vars in a recent agent release and neglected to update the README . The doc should be fixed now, thanks for catching it!
