### ISSUE TITLE
Memcache check not working on Python2

### ISSUE THREAD

**Issue by bjeanes** [DataDog/heroku-buildpack-datadog#104]
Hi, I have a `mcache.yaml` file set up as per the README. I can confirm that the file is being moved into DD's expected directory:

```
$ heroku run cat /app/.apt/etc/datadog-agent/conf.d/mcache.d/conf.yaml
Running cat /app/.apt/etc/datadog-agent/conf.d/mcache.d/conf.yaml on ⬢ covidence-datadog-metrics... up, run.5601 (Hobby)
WARNING: DD_HOSTNAME has been set. Setting this environment variable may result in metrics errors. To remove it, run: heroku config:unset DD_HOSTNAME
Starting Datadog Agent on service-metrics-collector
The Datadog Trace Agent has been disabled. Set DD_APM_ENABLED to true or unset it.
---
init_config:
instances:
- url: REDACTED.heroku.prod.memcachier.com
  username: 960FD1
  password: REDACTED
  port: 11211
  tags: []
```

The associated metrics are not appearing in DD UI nor is the infrastructure list reporting this host as emitting these checks/metrics.

Am I missing something?

**Comment by bjeanes** [comment]
I'd also really love to be able to set the `host` on a per-check basis. The fact that I can't run the agent on my Postgres, Redis, ElasticSearch, or Memcache machines directly is just a matter of course for using hosted providers. I therefore run a dedicated Heroku app which connects to each of these to slurp in the appropriate metrics, but then the `host` is misleading.

Weirdly, your ElasticSearch check _does_ seem to replace the host with the appropriate node in the ES cluster (so works as I'd like), but the others do not :(

**Comment by bjeanes** [comment]
```
Datadog's mcache integration is reporting:
Instance #initialization[ERROR]:{"Core Check Loader":"Check mcache not found in Catalog","JMX Check Loader":"check is not a jmx check, or unable to determine if it's so","Python Check Loader":"Traceback (most recent call last):\n File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mcache/__init__.py\", line 5, in \u003cmodule\u003e\n from .mcache import Memcache\n File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mcache/mcache.py\", line 6, in \u003cmodule\u003e\n import pkg_resources\nImportError: No module named pkg_resources\n"}
```

**Comment by jyee** [comment]
@bjeanes Can you confirm which version of the Datadog Agent you're using?

You can see this when Heroku builds your slug and it should look something like:
```
Latest version is "6.10.1-1". To pin this version, run: heroku config:set DD_AGENT_VERSION=6.10.1-1
```

Or you can get a shell on a dyno and run `agent version` which should return something like:
```
$ agent version
Agent 6.10.1 - Commit: 5e1bec3 - Serialization version: 4.7.1
```

If you're running 6.9.x, we recommend upgrading to 6.10.1-1 (the latest version) or you can try rolling back to 6.8.3-1.

**Comment by bjeanes** [comment]
Confirmed it is 6.10.1-1. We deploy daily and don't have the version
pinned. I am still seeing this issue. Also, postgres metrics are only
partially being reported. E.g. connection counts and locks are reporting
but table sizes and freq scanned indices are not, even they used to be

**Comment by gauravmk** [comment]
I'm also hitting this. 

```
$ agent version
Agent 6.10.2 - Commit: e36980b - Serialization version: 4.7.1
```

In our logs i'm seeing
```
2019-03-24T02:55:38.624658+00:00 app[web.1]: 2019-03-24 02:55:38 UTC | ERROR | (pkg/collector/scheduler.go:184 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'mcache'
```

**Comment by gauravmk** [comment]
```
  Loading Errors
  ==============
    mcache
    ------
      Core Check Loader:
        Check mcache not found in Catalog

      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so

      Python Check Loader:
        Traceback (most recent call last):
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mcache/__init__.py", line 5, in <module>
    from .mcache import Memcache
  File "/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/mcache/mcache.py", line 6, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

is what I see if I run an agent status check

**Comment by arapulido** [comment]
For those having this issue. We are investigating why `pkg_resources` is not in our `python2` distribution. In the mean time, and if you are not running custom checks or your custom checks are python3 ready, a way to solve this is to move to python3 instead (which we recommend doing as soon as possible, anyway).

To do so, you will need to add the following env variable to your Heroku apps:

`DD_PYTHON_VERSION=3`

and then rebuild your slugs for that to take effect.
