### ISSUE TITLE
write: connection refused on udp:8125

### ISSUE THREAD

**Issue by abtris** [DataDog/heroku-buildpack-datadog#106]
Hi,
 I can upgrade https://github.com/apiaryio/heroku-datadog-drain-golang with support new buildpack and after testing deploy we get errors.

```
2019-04-23T15:52:47.206317+00:00 app[web.1]: time="2019-04-23T15:52:47Z" level=info msg="Failed to send Histogram" error="write udp 127.0.0.1:48481->127.0.0.1:8125: write: connection refused"
2019-04-23T15:52:47.206403+00:00 app[web.1]: time="2019-04-23T15:52:47Z" level=info msg="Failed to send Histogram" error="write udp 127.0.0.1:48481->127.0.0.1:8125: write: connection refused"
```
Old buildpack works fine. From docs I understand that statsd listen on 8125 is enabled by default?

**Comment by jyee** [comment]
@abtris Yes, the new agent listens on 8125 and that's enabled by default. The new buildpack requires a slightly different setup from Mike's original buildpack, so you may need to take a look at that. We can also take a look at it from our end to see if something else might be causing a problem.

**Comment by irabinovitch** [comment]
@abtris were you able to resolve the challenge you were experiencing?

**Comment by Masyaka** [comment]
@abtris Did you solve this problem? Now I have the same.

**Comment by arapulido** [comment]
Hello @Masyaka Did you start experiencing this when upgrading the agent or the buildpack? if yes, what versions? Thanks!

**Comment by Masyaka** [comment]
Hello @arapulido I`m setting up https://github.com/apiaryio/heroku-datadog-drain-golang for collecting heroku router stats. 
And I`m getting `127.0.0.1:8125: write: connection refused` in heroku logs. I`m thinking that I missing something in configuration.

**Comment by arapulido** [comment]
@Masyaka what version of the buildpack are you using?

**Comment by Masyaka** [comment]
> @Masyaka what version of the buildpack are you using?

Latest https://github.com/DataDog/heroku-buildpack-datadog.git

**Comment by abtris** [comment]
@Masyaka We don't have time to investigate and just rollback to previous version.

**Comment by Masyaka** [comment]
Thanks

**Comment by abtris** [comment]
I think looks like `bind_host` is some different that in old version. But can't find any difference what can cause issue. `bind_host` have to be set to `0.0.0.0` but that can problem with permissions, sometimes is better to set to `localhost` instead.

**Comment by Masyaka** [comment]
Problem is solved. I was using `DATADOG_API_KEY` (wrong) env key instead of `DD_API_KEY`. With `DD_API_KEY` logs parser works fine.

**Comment by abtris** [comment]
They just change name API KEY? Ohh, no. Thanks.

**Comment by arapulido** [comment]
OK, thanks for the input. I will close this issue now. Thanks @abtris for opening the related issue.
