### ISSUE TITLE
prerun.sh adding DD_TAGS breaks already-set DD_TAGS

### ISSUE THREAD

**Issue by Daenyth** [DataDog/heroku-buildpack-datadog#109]
I wanted to get dyno class (1X, 2X,..) in my tags, so I added this to my prerun.sh:

```bash
# ulimit logic taken from heroku jvm-common buildpack
# https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/opt/jvmcommon.sh
case $(ulimit -u) in
  512)   # 2X, private-s
    DYNOCLASS="2X"
    ;;
  16384) # perf-m, private-m
    DYNOCLASS="PM"
    ;;
  32768) # perf-l, private-l
    DYNOCLASS="PL"
    ;;
  *) # Free, Hobby, 1X
    DYNOCLASS="1X"
    ;;
esac

DD_TAGS="$DD_TAGS dynoclass:$DYNOCLASS"
```

This caused the datadog agent to ignore the DD_TAGS I had in my `heroku config`. I realized it's because of this series of events:

- heroku config sets DD_TAGS=env:staging,...
- datadog.sh parses DD_TAGS into datadog.yaml
- datadog.sh unsets DD_TAGS
- datadog.sh sources prerun.sh (adding our tags)
- datadog agent sees a non-unset DD_TAGS and ignores the tags in its config file (env,..)

**Comment by jyee** [comment]
I'm going to close this and merge with #102, which is the same issue.
