### ISSUE TITLE
datadog replaces the paths to certs

### ISSUE THREAD

**Issue by jughead** [DataDog/heroku-buildpack-datadog#115]
Since today new apps has incorrect certs configuration. With the current behavior all https requests fails. I've tried to use the previous version of datadog agent by specifying DD_AGENT_VERSION=6.11.3-1, but it didn't help.

#### Expected
```
OpenSSL::X509::DEFAULT_CERT_FILE  
=> "/usr/lib/ssl/cert.pem"
irb(main):010:0> OpenSSL::X509::DEFAULT_CERT_DIR
=> "/usr/lib/ssl/certs"
```

#### Actual
```
irb(main):024:0> OpenSSL::X509::DEFAULT_CERT_FILE                
=> "/opt/datadog-agent/embedded/ssl/cert.pem"
irb(main):025:0> OpenSSL::X509::DEFAULT_CERT_DIR
=> "/opt/datadog-agent/embedded/ssl/certs"
```

#### Environment
Ruby 2.4.4
Stack: Heroku-16

**Comment by pawelniewie** [comment]
Thanks @jughead for reporting this, I faced the same problem today.

**Comment by Jcambass** [comment]
We faced the issue that all outbound connections would fail with an 
`certificate verify failed (unable to get local issuer certificate)`.

I believe that the problem is caused by a recent change that causes `datadog-agents` embedded SSL version to be used instead of the system ones. 

Recent change: https://github.com/DataDog/heroku-buildpack-datadog/commit/931fe948897d9d929aae736a6f649bef1fac0cdc

**Comment by rpc4mv** [comment]
We are also facing issues similar to what @Jcambass describes. Luckily the third party api calls we're making aren't critical and we're able to disable them temporarily, but it's not ideal. Please advise on how to resolve the issue, thanks!

**Comment by Jcambass** [comment]
@rpc4mv For now, I would suggest that you specify a specific commit of build pack to use in heroku. 

You can specify the version (branch, tag or commit SHA) something like this: 

```
https://github.com/DataDog/heroku-buildpack-datadog.git#afbdcd68e6f61affddab58ba14ed1d1ca11e6cb7
```

This would use the [latest commit without the bug](https://github.com/DataDog/heroku-buildpack-datadog/commit/afbdcd68e6f61affddab58ba14ed1d1ca11e6cb7) was introduced.

Also see [The Heroku docs for Using a third-party buildpack](https://devcenter.heroku.com/articles/buildpacks#using-a-third-party-buildpack)

**Comment by cbliard** [comment]
We faced this issue as well.

It broke our OAuth authentication and other stuff relying on external services. We stuck to 1.6.2 with `https://github.com/DataDog/heroku-buildpack-datadog.git#1.6.2` to fix the issue.

**Comment by itsNikolay** [comment]
Also it was affected on Elastic Search
```
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
<truncated 66 additional frames>
```

**Comment by jwg2s** [comment]
Also suffering from this - @cbliard's suggestion of pinning to v1.6.2 resolved the issue for us. This seems like an issue that needs an urgent hotfix.

**Comment by jeremy-lq** [comment]
Thanks for the bug reports. We're actively looking into this now and will be rolling out a fix ASAP.

**Comment by jeremy-lq** [comment]
https://github.com/DataDog/heroku-buildpack-datadog/pull/117 fixed the issue in our test environment. We're rolling this out now. If it doesn't fix the issue for anyone, please let us know. We apologize for the inconvenience.

**Comment by austinh** [comment]
@jeremy-lq master doesnt seem to fix the issue for me. but pinning to https://github.com/DataDog/heroku-buildpack-datadog.git#1.6.2 does

**Comment by jeremy-lq** [comment]
@austinh Which Stack are you using, 16 or 18?

**Comment by austinh** [comment]
@jeremy-lq using heroku stack 18.

**Comment by Jcambass** [comment]
@jeremy-lq I think that `LD_LIBRARY_PATH` will be searched before the usual library directories. Not an expert at all but I would assume that the normal OpenSSL binary is not included there.

So adding `$APT_DIR/opt/datadog-agent/embedded/lib` to `LD_LIBRARY_PATH` will always cause the embeeded OpenSSL version to be loaded.

**Comment by jeremy-lq** [comment]
@Jcambass We've been careful to preserve your existing LD_LIBRARY_PATH earliest in the precedent.
@austinh Thanks

We'll have a further update ASAP.

**Comment by Jcambass** [comment]
@jeremy-lq I think you kinda missed my point. I just double checked and `openssl` is normally not loaded from `LD_LIBRARY_PATH` so if you include it in there it will get loaded from there since `LD_LIBRARY_PATH` will always be searched BEFORE the normal paths.

![image](https://user-images.githubusercontent.com/3436381/60524777-770c7c80-9ced-11e9-89bd-650f52907477.png)

**Comment by jeremy-lq** [comment]
@Jcambass https://github.com/DataDog/heroku-buildpack-datadog/pull/118 incoming.

**Comment by calston** [comment]
#117 broke our entire production stack. I am unamused, why are you messing with the system SSL libraries?

**Comment by jeremy-lq** [comment]
#118 has passed all tests on Heroku-16 and Heroku-18 and has been merged.

@calston Our apologies. To confirm, we did not touch system SSL libraries in any way. The previous buildpack changed the order libraries were loaded, causing the Datadog OpenSSL library to take precedence.

**Comment by Szeliga** [comment]
I can confirm that everything is working for the following stack:
* heroku-18
* agent version - 6.11.3-1
* buildpack version - 1.6.3

**Comment by jughead** [comment]
The latest commit works for me too. I will close the ticket, feel free to reopen.

**Comment by Jcambass** [comment]
@jughead Are there any plans to release a new version that includes this bugfix soonish?

**Comment by jughead** [comment]
I don't know, I am not a maintainer :)

**Comment by jeremy-lq** [comment]
@jughead @Jcambass I've released https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/1.6.4 with the fix.
