### ISSUE TITLE
A little note when using heroku-buildpack-monorepo

### ISSUE THREAD

**Issue by pbernery** [DataDog/heroku-buildpack-datadog#143]
If one uses a buildpack like https://github.com/lstoll/heroku-buildpack-monorepo, the installation instruction of DataDog won't work.

The monorepo buildpack replaces the /app directory with the content of a subdirectory of the repository. But the DataDog buildpack also installs things in the /app directory.
If added in the order in the DataDog documentation, the /app directory won't contain the DataDog stuff.

In my case, the solution was to move the DataDog buildpack after the monorepo one.

Maybe a note in the documentation could help others?

**Comment by tnolet** [comment]
@pbernery o wow. Was just debugging this. Can not get any metrics into Datadog now with the monorepo buildpack.

**Comment by arapulido** [comment]
Thanks @pbernery for your report and your solution! We will indeed add a note about this in our documentation. @tnolet did moving the DD buildpack after the monorepo one work for you?

**Comment by tnolet** [comment]
@arapulido I ended up not using Datadog because of this basically

https://twitter.com/tim_nolet/status/1192832519034621953

Having to shell out for a host when I'm not getting any relevant data from it is a no go for me, so I'm looking for another APM solution
