### ISSUE TITLE
find: missing argument to `-name'

### ISSUE THREAD

**Issue by randy-girard** [DataDog/heroku-buildpack-datadog#154]
I recently pushed a new version of my code and I started getting this error when trying to run anything in the container. `flynn run bash` for example.

`find: missing argument to `-name'`

I removed this buildpack and it started working. Looks like there was a recent change causing this.

Note: It is working on Heroku fine, but fails on Flynn.

**Comment by arapulido** [comment]
Hello @randy-girard Thanks for reporting this. I think I know what might be causing this. While I have time to investigate and fix, you can work around it by using the previous buildpack release: `https://github.com/DataDog/heroku-buildpack-datadog.git#1.10`

**Comment by randy-girard** [comment]
That works. Thanks!
