### ISSUE TITLE
Provides dd-agent but not datadog-agent

### ISSUE THREAD

**Issue by jd** [DataDog/heroku-buildpack-datadog#157]
This is at least confusing:

```
~ $ dd-agent
The deprecated binary 'dd-agent' is no longer provided. Please use the 'datadog-agent' binary instead.
~ $ datadog-agent
-bash: datadog-agent: command not found
```

**Comment by arapulido** [comment]
@jd This is related on how Heroku buildpacks work, which I agree that is less than ideal. We have this documented. To run the agent commands: https://github.com/DataDog/heroku-buildpack-datadog#debugging Let me know if this helps

**Comment by jd** [comment]
Yeah it might be fine to have this set up this way, my main "complaint" here is that the UX is should be improved so it's clear for everyone what to do. :)

**Comment by arapulido** [comment]
Closing this issue, as it is minor, and we have a lot of restrictions of what we can do with the Heroku filesystem
