### ISSUE TITLE
DD_TAGS expects a comma as a separator

### ISSUE THREAD

**Issue by jd** [DataDog/heroku-buildpack-datadog#160]
In this buildpack the `DD_TAGS` wants tags to be separated with a comma `,`.

It seems to me that this is not what every other `DD_TAGS` usage does in other parts of the product. A single space is enough. This is quite confusing.

**Comment by jeremy-lq** [comment]
Agreed, this should match the behavior of `DD_TAGS` elsewhere. @arapulido let's maintain backward compatibility, but update docs/functionality to default to space delimited.
