### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by steakchaser** [DataDog/heroku-buildpack-datadog#163]
Using the latest version of the Heroku buildpack, running agent version `7.16.0-1`, I see the following error in the logs on startup (web and worker):

> 2019-12-28T16:15:30.522560+00:00 app[web.1]: Starting Datadog Agent on my-app-rails-staging.web.1
> 2019-12-28T16:15:30.540196+00:00 app[web.1]: Starting Datadog Trace Agent on my-app-rails-staging.web.1
> 2019-12-28T16:15:32.232625+00:00 app[web.1]: 2019-12-28 16:15:32 UTC | CORE | ERROR | (pkg/logs/auditor/auditor.go:159 in recoverRegistry) | open /opt/datadog-agent/run/registry.json: no such file or directory

Configured as follows:
```
DD_AGENT_MAJOR_VERSION:       7
DD_APM_ENABLED:               true
DD_DYNO_HOST:                 true
DD_LOGS_ENABLED:              true
DD_LOG_LEVEL:                 ERROR
```

**Comment by arapulido** [comment]
Hello @steakchaser !

The `DD_LOGS_ENABLED` is an option to enable log collection from the datadog agent. Unfortunately, log collection is not supported by the Heroku buildpack (https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#heroku-log-collection). 

You can forward the Heroku logs to Datadog, though, by following this guide: https://docs.datadoghq.com/logs/guide/collect-heroku-logs/?tab=ussite

To remove the error that you are getting, remove the `DD_LOGS_ENABLED` option.

I hope this helps.

**Comment by steakchaser** [comment]
Hi @arapulido !  Are you sure about this?  I was able to collect logs just fine using the datadog agent.  If I switch over to the log drain, I lose the nice parsing that the Ruby log pipeline provides.

**Comment by steakchaser** [comment]
@arapulido the problem I'm facing is that the log drain requires picking one `ddsource`, but the log stream contains logs generated by `Heroku` and my Rails app via [lograge](https://github.com/roidrage/lograge).  I need to be able to parse these logs differently - one using the Heroku pipeline and one using the Ruby pipeline.

**Comment by arapulido** [comment]
Hello @steakchaser 

Several things: for the log drain, currently is not possible to set different sources, sorry.

For the actual logger, I have created a patch (#167) to fix the path for log collector run path. I will create a new release with the fix, but if you want to try, you can add the following option to your `datadog.yaml` file:

`log_config.run_path: /app/.apt/etc/datadog/run`

You will still see that error once (this is a known issue with the agent), but you will have the correct path setup.

**Comment by arapulido** [comment]
With the new release of the buildpack being out, and with the original error being fixed in the agent (https://github.com/DataDog/datadog-agent/pull/4763), I will close this issue.

@steakchaser Feel free to open a new one if logging with `DD_LOGS_ENABLED` doesn't work for you with the latest release (`1.14`)
