### ISSUE TITLE
How use this buildpacks with Git-subtree

### ISSUE THREAD

**Issue by alvaaz** [DataDog/heroku-buildpack-datadog#165]
Hi, I've a project with backend and folder folder in the same directory:

```
project
---frontend
---backend
```

Actually, to deploy in heroku I've two remotes (frontend, backend) and two apps. To deploy use git-subtree

`git subtree push --prefix <path/to/subdirectory> <remote> master`

When try to add this buildpacks I can't

somebody could help me?

**Comment by arapulido** [comment]
Hello @alvaaz ! Can you explain a bit more what error do you get? What are the buildpacks that you are using and how are you trying to add the Datadog buildpack. Thanks!

**Comment by alvaaz** [comment]
Hi,

My app in Heroku has the following structure

```
project
---frontend
---backend
```
To deploy frontend I use the following script

`git subtree push --prefix frontend heroku master`

To add datadog-buildpack followed the Datadog's instructions. 

1. Add buildpacks to my exist app
2. The buildpacks list has: heroku/nodejs and datadog-heroku
3. Enable Heroku Labs Dyno Metadata
4. Add the buildpack and set Datadog API key
5. Deploy with subtree.

It is deploy but the application shows an error. When I try to add the buildpacks this error appeared:

```
Error: Multiple apps in git remotes
 ›      Usage: --remote heroku
 ›         or: --app jumpittlabs-site-front
 ›      Your local git repository has more than 1 app referenced in git remotes.
 ›      Because of this, we can't determine which app you want to run this command against.
 ›      Specify the app you want with --app or --remote.
 ›      Heroku remotes in repo:
 ›      jumpittlabs-site-cms (backend)
 ›   jumpittlabs-site-front (heroku)
```
That's why I always use 

`--remote heroku`

**Comment by arapulido** [comment]
This is not related to our buildpack, but just an error in your configuration. 

Did you select the remote when adding the buildpacks?

We have a testing application for this repository that actually uses git subtree and has two different applications (and uses our buildpack): https://github.com/DataDog/heroku-buildpack-datadog-testing/blob/master/buildpack-test.sh#L50

You can check there how we do it and see if that helps

**Comment by alvaaz** [comment]
Yes, I selected the remote.

The repository no exist or I haven't access. 

Could you send me a code capture?

**Comment by arapulido** [comment]
@alvaaz sorry, basically what we do is the following:

```
heroku buildpacks:clear --remote <your_first_remote>
heroku buildpacks:add <your_buildpack> --remote <your_first_remote>
heroku buildpacks:add https://github.com/DataDog/heroku-buildpack-datadog --remote <your_first_remote>

git push <your_first_remote> "$(git subtree split --prefix <your_folder_with_code> master)":master
```

**Comment by alvaaz** [comment]
I followed the instructions but it shows me the same error:

https://imgur.com/8BZYBfr

```
2020-01-14T15:29:44.513962+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=jumpittlabs-site-front.herokuapp.com request_id=4698-90547348c6219186-94253-ca7a-7d7 fwd="178.231.93.152" dyno= connect= service= status=503 bytes= protocol=https
2020-01-14T15:31:57.000000+00:00 app[api]: Build started by user ag@jumpitt.com
2020-01-14T15:34:06.018303+00:00 app[api]: Release v25 created by user ag@jumpitt.com
2020-01-14T15:34:06.018303+00:00 app[api]: Deploy 5884e13d by user ag@jumpitt.com
2020-01-14T15:34:22.000000+00:00 app[api]: Build succeeded
2020-01-14T15:34:32.432376+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=jumpittlabs-site-front.herokuapp.com request_id=1f51a028-cc59-469d-b38a-8a64a38f829c fwd="152.231.93.178" dyno= connect= service= status=503 bytes= protocol=https

```
When I deploy without this buildpacks there is no error. The project es a App in Next.js.

**Comment by arapulido** [comment]
@alvaaz were you able to make this work? What is the output when building the slug?

**Comment by arapulido** [comment]
@alvaaz We didn't hear back from you, so I am closing this issue now. Please, reopen if you still have this issue
