### ISSUE TITLE
Ignore scheduler resource

### ISSUE THREAD

**Issue by rodosskiand** [DataDog/heroku-buildpack-datadog#166]
# How i can ignore scheduler instances for monitoring?

i noticed variable: ```DD_IGNORE_HOST```

i tryed set 

```
DD_IGNORE_HOST=eva-eventures.scheduler.*
```
and

```
DD_IGNORE_HOST=eva-eventures.scheduler
```

But it doesnt working

**Comment by arapulido** [comment]
Hello @rodosskiand 

The way to do this in the Heroku buildpack is by using the `prerun.sh` script. You can see an example of doing this but for `run` instances in our documentation:

https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#prerun-script

**Comment by rodosskiand** [comment]
Thanks, it works!
