### ISSUE TITLE
Collecting system metrics for dynos

### ISSUE THREAD

**Issue by rodosskiand** [DataDog/heroku-buildpack-datadog#171]
Hello. I find it a little difficult with creating custom metrics from logs. I enabled og-runtime-metrics and it successfully shows in logs, but ш do not quite understand how to create metrics from it. When i try to create metic i not see these parametres: memory_rss, memory_cache , etc.

Possibly provide values from logs:

```
source=slow_worker.1 dyno=heroku.106896708.ec6bc634-6562-4185-a6f7-f4570e3088ff sample#load_avg_1m=0.00 sample#load_avg_5m=0.02 sample#load_avg_15m=0.02
```

to dashboard?

**Comment by jeremy-lq** [comment]
Hello, the documentation to create metrics from logs can be found here: https://docs.datadoghq.com/logs/logs_to_metrics/

If you need further support on this, please open a support ticket and someone will walk you through it.
