### ISSUE TITLE
Docs might need updating re: conf.d paths that work with this buildpack

### ISSUE THREAD

**Issue by aguynamedben** [DataDog/heroku-buildpack-datadog#174]
Hi, I tried using Datadog + Heroku for the first time today and found something in the docs that could probably be improved.

My goal was to setup Datadog, lograge, and Heroku via this latest buildpack (1.15). In [this guide](https://docs.datadoghq.com/logs/log_collection/ruby/), it says:
> Configure your Datadog Agent. Create a ruby.d/conf.yaml file in your conf.d/ folder with the following content

In the context of the Heroku buildpack, I interpreted this to mean `myapp/datadog/conf.d/ruby.d/conf.yaml`, which didn't work. But the docs for the buildpack say to put that sort of config in `myapp/datadog/conf.d/ruby.yaml`, which is what eventually worked. It seems this guide should be updated to match the buildpack.

Here's my project's working `datadog/conf.d/ruby.yaml`:
```yaml
logs:
  - type: file
    path: /app/log/lograge_production.log
    source: ruby
    service: ruby
```

I'll probably further refine this from within lograge to use Heroku ENV vars to differentiate service (i.e. myapp-staging vs. myapp-production)

Also, this buildpack comes with logs_enabled off. I had to go poking around `heroku ps:exec` in `/app/.apt/etc/datadog-agent` and running `/app/.apt/opt/datadog-agent/bin/agent/agent-wrapper status` and bunch from within my `heroku ps:exec`. Finally I realized I needed to set `DD_LOGS_ENABLED=1` in my ENV variables.

This was doubly confusing because for whatever reason, each time `heroku ps:exec` starts I always say this message, making me doubt my ENV setup:
```
Establishing credentials... done
Connecting to web.1 on ⬢ myapp-staging...
DD_API_KEY environment variable not set. Run: heroku config:add DD_API_KEY=<your API key>
The Datadog Agent has been disabled. Unset the DISABLE_DATADOG_AGENT or set missing environment variables.
```
This output was just confusing. Maybe there could be better copy explaining if this disablement is just for the life of `heroku ps:exec`...?

Anyway, I got it all working in the end, but I think there could be better docs for this seemingly common combination:
* Heroku
* Rails
* lograge JSON logs
* I didn't want to use Heroku log drains because all the query parameters are logged from the Heroku router (including sensitive query parameters). With the lograge method Rails' `filter_parameter_logging.rb` kicks in ensuring that I don't log access tokens, etc. to Datadog.

**Comment by arapulido** [comment]
Hello @aguynamedben Thanks for the write-up and sorry it took you a bit longer to figure things out. Unfortunately, Heroku is somehow special, so the general instructions for VMs wouldn't work in Heroku.

So, we cannot change the general documentation to work with Heroku but, of course, we want the documentation that is Heroku specific to be as useful as possible.

My question to you would be:

If you had started by reading this documentation: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/ What would you have missed from that one to make your use case work?

Thanks!

**Comment by arapulido** [comment]
hello @aguynamedben ! I will close this one for now, but feel free to reopen if you have any specific suggestions on how we can improve our documentation. Thanks!

**Comment by aguynamedben** [comment]
This was a long time ago, so I forget what the details were, but maybe you should have a callout "Using Ruby on Rails with Heroku? Try our Heroku guide!" at the top of https://docs.datadoghq.com/logs/log_collection/ruby/ 🤷

**Comment by mixergtz** [comment]
@aguynamedben Thanks a lot for this issue, saved my a lot of time.

@arapulido I've recently configured an application with the same stack mentioned (Heroku, Rails, Lograge) and my thoughts on the current documentation are:

- This post doesn't make explicit that for Heroku and Rails, the `ruby.yaml` file should go into `/<your-rails-app-root-folder>/datadog/conf.d/`
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/

- This post doesn't mention Heroku at all
https://www.datadoghq.com/blog/managing-rails-logs-with-datadog/

- This is helpful to set Lograge with Rails, but again, doesn't mention Heroku
https://docs.datadoghq.com/logs/log_collection/ruby/

- This is really good and helpful
https://docs.datadoghq.com/tracing/connect_logs_and_traces/ruby/

- This post doesn't mention Heroku at all
https://www.datadoghq.com/blog/monitoring-rails-with-datadog/

- These two were helpful but it wasn't clear for me to determine when to implement them 
(at the beginning or after having configured the other things?)
https://docs.datadoghq.com/logs/guide/collect-heroku-logs/
https://docs.datadoghq.com/logs/logs_to_metrics/

I totally agree that centralizing the information around the combination of Heroku, Rails, Lograge should save tons of time
