### ISSUE TITLE
Add documentation on how to use custom checks

### ISSUE THREAD

**Issue by arapulido** [DataDog/heroku-buildpack-datadog#175]
We have documentation on how to enable pre-built integrations, but we are lacking documentation on how to add custom checks.

We should add documentation around it.

**Comment by christx2** [comment]
Hello for Heroku i have used a prerun script to ensure that:
1. the .yaml custom configuration is placed properly into heroku specific conf.d location /<heroku-app-root>/.apt/etc/datadog-agent/conf.d/<my-custom-agent>.d/conf.yaml

2. the .py agent code which needs to for Heroku in /<heroku-app-root>/.apt/etc/datadog-agent/checks.d/<my-custom-agent>.py

its not entirely clear in the existing documentation that is where the files need to end up from /<heroku-app-root>/datadog/conf.d  and check.d respectively to run on Heroku without any runtime errors or not starting at all.

**Comment by arapulido** [comment]
This is now available if you are using the buildpack from master and it will be available in the next release: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#enabling-custom-checks
