### ISSUE TITLE
heroku purge_cache not a valid command

### ISSUE THREAD

**Issue by IanVaughan** [DataDog/heroku-buildpack-datadog#177]
On https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#upgrading-and-slug-recompilation (from the readme here: https://github.com/DataDog/heroku-buildpack-datadog/search?q=purge_cache&unscoped_q=purge_cache)

It states to use `purge_cache` :
```
# Clears Heroku's build cache for "appname" application
heroku repo:purge_cache -a appname
```

But attempting that results in `not a heroku command`:
```bash
$ heroku repo:purge_cache
 ›   Warning: repo:purge_cache is not a heroku command.
Did you mean apps:create? [y/n]: n
```

version: `heroku/7.37.0 darwin-x64 node-v12.13.0`

**Comment by arapulido** [comment]
hey @IanVaughan ! You're correct, you need to add a plugin first. Please, follow the instructions at:  https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

I will update the instructions

**Comment by arapulido** [comment]
@IanVaughan mmm, I just realized the readme already includes the bit about installing the heroku-repo plugin. Did you install it and the command still fails?

**Comment by IanVaughan** [comment]
Really sorry, I completely missed that step...
Added it and it worked fine!
Cheers

**Comment by arapulido** [comment]
@IanVaughan No worries! Thanks for following up!
