### ISSUE TITLE
Sending application JSON-formatted logs using Heroku log drain or Datadog log agent

### ISSUE THREAD

**Issue by spchuang** [DataDog/heroku-buildpack-datadog#194]
I'm setting up datadog monitoring for my heroku applications and have gotten the Heroku log drain for system metrics. 

I'm wondering if I want to log application logs (JSON structured logs), would it be best to just pass it to Heroku log drain (stdout) or use the Datadog log agent (by enabling `DD_LOGS_ENABLED` and use DD log agents)?

**Comment by arapulido** [comment]
Both should be fine, but if you send them through the log drain, the source will be the same for every log, so it would be a little more difficult to distinguish from the system metrics one, and parse accordingly.

**Comment by arapulido** [comment]
@spchuang I will close now this, but feel free to reopen if you are having issues here. Thanks!
