### ISSUE TITLE
Option to launch datadog-agent from within heroku-ci

### ISSUE THREAD

**Issue by breathe** [DataDog/heroku-buildpack-datadog#206]
I'd like the equivalent of `agent-wrapper start` to be run after `heroku-buildpack-datadog` does its business -- so that any buildpack that runs after the heroku-buildpack-datadog has the ability to send messages to datadog ...  I'd like to track build times and other metrics during my CI execution ...   Is it possible?

**Comment by arapulido** [comment]
Mmm, I doubt this is possible. The agent runs in a dyno context, not the build context. So, when the datadog buildpack finishes, the Heroku slug is not yet ready (waiting for the rest of the buildpacks), so unable to get metrics at that point. Maybe you can try sending custom metrics directly to the Datadog's HTTP endpoint (https://docs.datadoghq.com/api/v1/metrics/#submit-metrics).

Even there, not sure if you can get the right data from Heroku. 

Let me know if you get something working! I would love to hear about it!

**Comment by arapulido** [comment]
@breathe did you find a workaround for this?

**Comment by arapulido** [comment]
hello @breathe Closing this for now. Feel free to reopen if you have a follow up on this. Thanks!
