### ISSUE TITLE
Documentation on integrations

### ISSUE THREAD

**Issue by khazidhea** [DataDog/heroku-buildpack-datadog#207]
Hi. It's not clear to me how to enable integrations.

It says to add a file `/datadog/conf.d/<INTEGRATION_NAME>.yaml` in the root of your application. First of all when it says `/datadog/` it looks like root of my system. 

Let's say my project is `/somewhere/in/my/system/`, I've added a file named `/somewhere/in/my/system/datadog/conf.d/python.yaml` - is this the correct location? I dont seem to be collecting any metrics this way. Is there something I'm doing wrong?

**Comment by arapulido** [comment]
Hello @khazidhea. That's the correct way to enable the integration, yes. The reason why you're not seeing metrics yet is because the Python integration doesn't collect any default metrics. That configuration file is actually used to point to a log file you want to parse. You can check the documentation here: https://docs.datadoghq.com/logs/log_collection/python/?tab=json_logformatter#configure-the-datadog-agent

You can learn more about metrics, traces and logs for Python at: https://docs.datadoghq.com/integrations/python/

I hope that answers your question

**Comment by khazidhea** [comment]
Hi and thanks for you response @arapulido 

The doc you linked seems to be specifically about parsing logs and it looks like I would have to manually log the events I'm interested in. That's not what I'm trying to do.

I've used datadog on a couple of other projects hosted on VPS using docker where I pretty much had full control. It was pretty easy for me to set up and see performance metrics like per function execution time for each request, I loved it.

Now I'm wondering how I can do the same for heroku - is it even possible? Right now all I can see in my APM is request latency, my gunicorn and python dashboars are empty and I'm not sure how to set this up

**Comment by arapulido** [comment]
The gunicorn board is part of the gunicorn integration, so you will need to set it up (create your configuration and copying it to /datadog/conf.d/gunicorn.yaml). You can check how to set it up here: https://docs.datadoghq.com/integrations/gunicorn/

Remember that you will need to add setproctitle to your app requirements and set up an app name in your Procfile and point to the dogstatsd server (i.e. `web: gunicorn --name hello --statsd-host 127.0.0.1:8125 hello_world:app`). I just tried this in my test app and I correctly started getting gunicorn metrics.

For the Python runtime metrics, this comes directly from APM. You need to set it up following the instructions here: https://docs.datadoghq.com/tracing/runtime_metrics/python/

**Comment by khazidhea** [comment]
@arapulido thank you. I followed all the docs and had it all set up correctly. 

But in my case the problem was due to "python ABI is not compatible, you need to recompile this module." error which I found in my heroku logs. It was caused by not updating the minor python version on our end.
