### ISSUE TITLE
Process for installing & configuring integrations

### ISSUE THREAD

**Issue by jyee** [DataDog/heroku-buildpack-datadog#21]
We need a way to install and configure Datadog Agent integrations. This should take into account both publicly available integrations (e.g. integrations extras) and custom integrations.

An easy way would be to move/link to integrations in the app's filestructure, but I don't really like the idea that someone has to include integration code inside their app. Ideally the integration code would be pulled from elsewhere and configs done via env vars.

**Comment by quinn** [comment]
@jyee have you thought more about this one? I think the most straightforward would be to have the agent look for configs within a specific directly in the app. I see why you say this is not ideal but anything else (that I can think of?) is very weird and complex due the nature of the heroku platform.

**Comment by Swizec** [comment]
Would be great if we could get support for this. There's a lot of great integrations I'd like to use and I don't mind, if the implementation is not the most ideal.

**Comment by jyee** [comment]
See #49

**Comment by jyee** [comment]
I've merged #49. This provides support to configure core Agent checks. We'll work on integrating custom checks in upcoming work.

**Comment by jyee** [comment]
Between the existing work and the new prerun.sh, it's possible to import custom checks. To do this, you'll need to:

1. Move/copy your check code into `/app/.apt/etc/datadog-agent/checks.d`
2. Add that path to the `DD_PYTHONPATH` variable using the `prerun.sh`

For more information, see the documentation at https://docs.datadoghq.com/developers/write_agent_check/?tab=agentv6
