### ISSUE TITLE
Error waiting for network: Resource temporarily unavailable

### ISSUE THREAD

**Issue by barberj** [DataDog/heroku-buildpack-datadog#221]
# Bug

Still flushing out details, but Heroku has determined the issue to be with the datadog build pack.

I have a few background processes that have the DataDog agent disabled. Whenever I deploy all the background instances error `Error waiting for network: Resource temporarily unavailable`. I must stop all the instances and one by one turn them with a buffer between each.

Opening for early eyes and see if anyone else has heard/seen/experienced this as I attempt to flush out more details.

**Comment by arapulido** [comment]
Hello @barberj ! Any updates on this issue? Do you have more information?

**Comment by barberj** [comment]
No... I guess close. Heroku says it sometimes happens on background jobs... although sometimes is everytime for me. The pointed the blame at DataDog, but I'm not sure.
