### ISSUE TITLE
gauge data points are randomly multiplied by 2 or 3 on time frames >= 7 days 

### ISSUE THREAD

**Issue by MathieuDerelle** [DataDog/heroku-buildpack-datadog#222]
take a look at our graph : (time frame is 7 days)

![image](https://user-images.githubusercontent.com/16286023/98351043-793ac580-201c-11eb-8134-0e3b7e67ad62.png)

- on the left of the vertical line, we are using this official buildpack
- on the right of the vertical line, we are using this buildpack : https://github.com/miketheman/heroku-buildpack-datadog.git

(nothing else has changed)

It only affects large time frames.
When using time frame of 2 days or less, this random effect dissapear.

**Comment by arapulido** [comment]
Hello @MathieuDerelle ! Thanks for your bug report. I have a question, what version of the datadog agent (not the buildpack, but the agent) are you running in each of those cases? Thanks!

**Comment by arapulido** [comment]
Hello @MathieuDerelle ! Any updates on this issue? Thanks!

**Comment by arapulido** [comment]
Hello @MathieuDerelle I will be closing this one for now. Let us know when you have more information about this. Thanks!
