### ISSUE TITLE
Update usage instructions to no longer pin buildpack version

### ISSUE THREAD

**Issue by edmorley** [DataDog/heroku-buildpack-datadog#229]
Hi!

As mentioned in #228, we recently had a customer open a support ticket who encountered the Heroku-20 error in #216, since they were pinned to the older v.1.17 buildpack release, which doesn't have Heroku-20 support.

Heroku buildpacks are something that most users tend to "set and forget", so whilst in general pinning versions of a thing would be recommended, for buildpacks we recommend against it, otherwise it makes it very hard to push out urgent fixes. This obviously means the buildpack needs to be more mindful of breaking changes (eg either avoiding them, or using a combination of warnings-in-advance, opt-in changes, and clear error messaging when breaking changes are made), but it's normally worth the trade-off.

As such, would it be possible to update the docs here, to remove the version pinning?
https://github.com/DataDog/heroku-buildpack-datadog/blame/2a5b7d7e62185a62c38c7bf6fd86e25fb172956e/README.md#L22

The current pinning usage example was added in #120, since at the time the Heroku docs did suggest pinning, however they've seen been updated to recommend only pinning for debugging:
https://devcenter.heroku.com/articles/buildpacks#buildpack-references

Advanced users can still choose to pin should they wish (plus any customers who encounter a breaking change can always pin retrospectively).

Many thanks :-)

**Comment by edmorley** [comment]
We've just had another customer attempting to upgrade to Heroku-20 experience issues due to the pinned buildpack version.

**Comment by edmorley** [comment]
@arapulido many thanks for this and #228.

**Comment by arapulido** [comment]
@edmorley thanks to you for reporting!
