### ISSUE TITLE
How to install integration-extras? 

### ISSUE THREAD

**Issue by jeffblake** [DataDog/heroku-buildpack-datadog#239]
I found this issue https://github.com/DataDog/heroku-buildpack-datadog/issues/21

But it doesn't have an answer on how to install publicly available integrations from https://github.com/DataDog/integrations-extras/

Ideally these are automatically updated and I wouldn't have to copy code into my app.

**Comment by arapulido** [comment]
If you exec into your dyno, you can execute: `agent-wrapper integration install -t datadog-<INTEGRATION_NAME>==<INTEGRATION_VERSION>` and that will install a specific version of the integration that has been released.

But I agree there should be a way so this is done automatically when starting/restarting dynos (and documented). I will work on this.

**Comment by arapulido** [comment]
Actually, you can run that command in the prerun.sh script and you are good to go. I will document this

**Comment by jeffblake** [comment]
Thanks, this works great!
