### ISSUE TITLE
Disabling integration checks on extra dynos?

### ISSUE THREAD

**Issue by jeffblake** [DataDog/heroku-buildpack-datadog#241]
I have postgres and redisdb checks installed. By default, all of these checks would run on every dyno (web, worker, etc), but postgres and redisdb don't run in the dyno, so I think it would make sense to only enable these integrations on the first web dyno. Is that right? How can it be done?

**Comment by rvisuvasam** [comment]
I'm having some success in rewriting the sample `prerun.sh` with this conditional instead (right before doing the PG variable replacement):
```
if [ -n "$DATADOG_PG_URL" ] && [ "$DYNO" == "worker.1" ]
```

**Comment by arapulido** [comment]
This is now documented: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#disabling-integrations-based-on-dynos
