### ISSUE TITLE
Question: Are the docs about having to clear the build cache accurate?

### ISSUE THREAD

**Issue by dgollahon** [DataDog/heroku-buildpack-datadog#242]
I noticed that in the latest release a changelog item was:

> Heroku APT cache is now cleaned up automatically when DD_AGENT_VERSION changes

Is this different from the heroku build cache? Or does this mean that changing `DD_AGENT_VERSION` changes still require installing `heroku-build` and purging? Also, if there are multiple apps in a pipeline or pipeline stage, does this need to be done for each app? Likewise, if that changelog entry does mean that this is automatically taken care of, does that apply for `DD_MAJOR_VERSION`?

I tried to look through the git history a bit to see what changed or why this is necessary but I don't know enough from a few minute skim.

I want to upgrade to the 7.x agent but was surprised to find there were extra steps involved in doing so. What happens if the build cache is not purged? I can purge the build cache for each of my apps but was just curious to learn more and if it is still necessary to do.

**Comment by arapulido** [comment]
Hello @dgollahon Thanks for the question. We will investigate this a bit further and will fix the documentation if needed. I think that you might be right, but let me double check.

**Comment by arapulido** [comment]
Hello again. Looking a bit more into this, I agree that the documentation needs to be clearer. The clean up that we automatically do when changing the version of the agent is the APT cache (that lives inside the heroku build cache). The reason why we do this is to avoid keeping a lot of very large files in the cache, something that may slow down builds (see warning here: https://devcenter.heroku.com/articles/buildpack-api#caching).

But this is now automatically done and just for the needed APT cache, so no longer recommended (or needed) to clean the full cache. I will fix the documentation to make this clearer.

That said, upgrading to a newer version of the agent do require rebuilding your app (but you don't need to clear the cache if you don't want to).

**Comment by dgollahon** [comment]
Cool, that makes more sense to me. Thanks @arapulido.
