### ISSUE TITLE
How do you pin a new version of the buildpack?

### ISSUE THREAD

**Issue by bradical** [DataDog/heroku-buildpack-datadog#247]
I see the example given here for upgrading: https://github.com/DataDog/heroku-buildpack-datadog#upgrading-and-slug-recompilation but I'm unclear what command to use to pin a new version of the buildpack itself.

**Comment by arapulido** [comment]
Hello! This is how you do it: https://github.com/DataDog/heroku-buildpack-datadog#pinning-a-specific-buildpack-version-and-a-specific-datadog-agent-version

I will close this now, but please reopen, if you have further questions.

**Comment by bradical** [comment]
Hmm, but if I already have a buildpack added will that replace the existing one or add a new one?

**Comment by arapulido** [comment]
You will need to delete the previous one and add the new one
