### ISSUE TITLE
Conditional conf.d's (e.g. gunicorn)

### ISSUE THREAD

**Issue by wbobeirne** [DataDog/heroku-buildpack-datadog#248]
I'm using the buildpack with a python server that uses gunicorn for the web, but also has celery dynos. When I add `gunicorn.yaml`, it tries to run it on all dynos, the celery ones included, so they get flooded with:
```
UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:122 in LogMessage) | gunicorn:bb78ac007a3a42b3 | (gunicorn.py:142) | No gunicorn process with name [name] found
```
Ideally I'd only use this config on my web workers. Is there a good way to do this, or will I have to do something funky in `prerun.sh`?

**Comment by wbobeirne** [comment]
I tried adding the following to my prerun.sh, but it doesn't seem to work:
```
# Disable gunicorn integration in non-web dynos
if [[ "$DYNO" != *"web"* ]]; then
  export DD_TRACE_GUNICORN_ENABLED="false"
fi
```
It's setting the env var, so it seems that ddtrace isn't respecting this variable for some reason.

**Comment by aburgel** [comment]
i was able to fix this by removing the gunicorn config file in the prerun script:

```sh
if [ "$DYNOTYPE" != "web" ]; then
  rm -f "$DD_CONF_DIR/conf.d/gunicorn.d/conf.yaml"
fi
```

**Comment by arapulido** [comment]
This is now documented: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#disabling-integrations-based-on-dynos
