### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by TimotheeVille** [DataDog/heroku-buildpack-datadog#254]
Hi there,

While building the app, I got this gpg error. Is there something I can do to solve that?

```bash
=====> Downloading Buildpack: https://github.com/DataDog/heroku-buildpack-datadog.git
=====> Detected Framework: Datadog
-----> Detected Stack and/or agent version changes, flushing cache
-----> Install gpg key for Datadog APT Repository
gpg: keybox '/tmp/cache/apt/temp.gpg' created
gpg: /tmp/cache/apt/trusted.gpg: trustdb created
gpg: key D3A80E30382E94DE: public key "Datadog, Inc <package@datadoghq.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
-----> Updating apt caches for Datadog Agent
Ign:1 https://apt.datadoghq.com stable InRelease
Hit:2 https://apt.datadoghq.com stable Release
Get:3 https://apt.datadoghq.com stable Release.gpg [819 B]
Ign:3 https://apt.datadoghq.com stable Release.gpg
Reading package lists...
W: GPG error: https://apt.datadoghq.com stable Release: The following signatures were invalid: BADSIG 4B4593018387EEAF Datadog, Inc <package@datadoghq.com>
E: The repository 'https://apt.datadoghq.com stable Release' is not signed.
!     An error occured during buildpack compilation
 !   Error deploying the application
!   → Invalid return code from buildpack
```

**Comment by arapulido** [comment]
Hello! This seems to be a regression from the previous version. I would like to get some answers to understand why this is failing for you, but for now, and to unblock you, can use the previous version of the buildpack:

```
heroku buildpacks:add --index 1 https://github.com/DataDog/heroku-buildpack-datadog.git#1.24
```
(removing the previous one)

What Heroku stack are you using for your application? Thanks!

**Comment by TimotheeVille** [comment]
Thanks, I will try that thank you!

I'm on a heroku like platform called [Scalingo](https://scalingo.com/). We are using the [scalingo-18 stack](https://doc.scalingo.com/platform/internals/stacks/scalingo-18-stack) (the default one)

**Comment by arapulido** [comment]
@TimotheeVille 

Thanks for the info.

Before changing the buildpack, can you see if cleaning your build cache solves the issue?

To clean your build cache you can do the following: https://doc.scalingo.com/platform/deployment/cache

Thanks!
Ara

**Comment by TimotheeVille** [comment]
@arapulido

Cleaning the cache fixed the issue!! Thank you so much.

**Comment by dkoloditch** [comment]
General build cache clear via the following instructions fixed it for us:

https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Namely:

```
heroku plugins:install heroku-builds -a appname
heroku builds:cache:purge -a appname -c appname
```

Confirmation flag required for purge.
