### ISSUE TITLE
CryptographyDeprecationWarning error during `heroku run bash`

### ISSUE THREAD

**Issue by mobilutz** [DataDog/heroku-buildpack-datadog#270]
I have a heroku app with the following buildpacks:
```
=== HEROKU_APP_NAME Buildpack URLs
1. https://github.com/DataDog/heroku-buildpack-datadog.git
2. heroku/metrics
3. heroku/ruby
4. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
```

When I start a [bash console](https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-run) on that app, I get the following error:
```
~ $ 2021-09-02 08:59:59 UTC | CORE | ERROR | (pkg/util/hostname/validate/validate.go:40 in ValidHostname) | ValidHostname: .run.2217 is not RFC1123 compliant
/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
```

Is this something that needs to be handled in this buildpack?

**Comment by arapulido** [comment]
@mobilutz we support both python2 and python3 in the agent. To change to python3, please add the following env variable to your Heroku application: `DD_AGENT_MAJOR_VERSION=7` Thanks!

**Comment by mobilutz** [comment]
@arapulido Will try this out next week. Thanks

**Comment by arapulido** [comment]
@mobilutz Closing this now. Please, reopen if switching to agent 7 didn't fix your issue
