### ISSUE TITLE
Using Custom Checks

### ISSUE THREAD

**Issue by DanielWright** [DataDog/heroku-buildpack-datadog#276]
There's a chunk of `datadog.sh` that [copies](https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L37-L48) the application's `conf.d` directory into the Agent's working directory. Is there a reason the same operation isn't done on `checks.d`?

**Comment by arapulido** [comment]
This is now available if you are using the buildpack from `master` and it will be available in the next release: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#enabling-custom-checks
