### ISSUE TITLE
How to enable Network Performance Monitoring?

### ISSUE THREAD

**Issue by bcomnes** [DataDog/heroku-buildpack-datadog#285]
Not sure if it even makes sense (just playing around and learning about DD), but how could I enable the network performance monitoring to work in Heroku? 

It says to set up a system-probe.yaml file. Does that work the same way integrations work as documented in the README?

**Comment by arapulido** [comment]
Hello @bcomnes ! Thanks for your question. Unfortunately,  network performance monitoring is not available for Heroku.

**Comment by bcomnes** [comment]
Cool thanks for the clarification.
