### ISSUE TITLE
Unable To Read Auth Token File: No Such File/Directory

### ISSUE THREAD

**Issue by Baron-burton** [DataDog/heroku-buildpack-datadog#302]
Hello 👋 

I've recently come across an issue when trying to use the `agent-wrapper` in my heroku console -- `heroku ps:exec`

When I attempt to run a command like `agent-wrapper status` I'm met with: 

```
Error: unable to read authentication token file: open /app/.apt/etc/datadog-agent/auth_token: no such file or directory
```

I'm not totally sure what's happening here or how to get more info. The agent should definitely be installed (it was previously working fine)

I've seen some people come across this in a slightly different form where the ddagent user doesn't have permission to access that file/directory. However, in this case, it's simply not being created. Is there a known fix for this?

**Comment by Baron-burton** [comment]
For added context, I only noticed this after checking changes I made to the prerun script. I wanted to disable tracing and profiling for spec dynos. While the agent was already turned off, the ddtrace agent would still attempt to send traces and then simply log errors. 

The script looks like: 

```if [ "$DYNOTYPE" == "run" ] || [ "$DYNOTYPE" == "scheduler" ] || [ "$DYNOTYPE" == "release" ]; then
  DISABLE_DATADOG_AGENT="true"
  
  # these two lines are my new additions
  DD_TRACE_ENABLED="false"
  DD_PROFILING_ENABLED="false"
fi
```

However, reverting my changes has had no effect on getting the agent to start back up again. I also don't see how this would've prevented the agent from starting on a web dyno anyway

**Comment by arapulido** [comment]
Hello @Baron-burton !

I am unable to reproduce your issue.

What version of the buildpack are you using? What's your Heroku stack? Also, are you pinning any specific version of the Datadog agent?

**Comment by Baron-burton** [comment]
@arapulido, sorry for the delay in responding. 

It's been so long that this was an issue and as far as I can tell we are not experiencing this anymore. I cannot say what actually fixed the issue for us as a number of people have since been working with Datadog in Staging. 

I'll re-raise an issue if this returns for us.
