### ISSUE TITLE
Question about logs and how to best configure - w/ this buildpack?

### ISSUE THREAD

**Issue by rsanheim** [DataDog/heroku-buildpack-datadog#303]
Hello! I had a general question about configuration and the state of heroku, datadog, and logs. I did search through old issues here and found some conflicting and/or outdated info.

It seems the [recommended way](https://docs.datadoghq.com/logs/guide/collect-heroku-logs/) to get logs going from Heroku to Datadog is to use a Heroku log drain.  This sends the heroku level logs, and will also send app logs that are routed to stdout via the drain. This works and is what I've setup for our app currently.

However, there is one significant problem: all logs collected via that drain have the same source `heroku`, and the same service name and same host, which are specified via the `heroku drain` command.

This means we lose a ton of visibility and traceability because all the logs basically come in from one coarse grained thing, and the router level logs get mixed up with the app level logs. It is possible to filter down a bit thru clever searching, and I know we could do our own attribute remapping, but that seems overly complicated and brittle.

Is there a better solution here I'm missing? Should we just route logs to the Heroku file system and use the DD buildpack + agent to send app level logs, and hope transient dynos don't cause a ton of problems with that? I feel like I may be missing something, but this default setup is severely lacking compared to a more traditional DD logging setup.

**Comment by arapulido** [comment]
@rsanheim Yes, this is currently a limitation on how Heroku log drains work. 

You could use the DD buildpack agent to send app level logs, but take into account that, because of how dyno filesystem works, creating a log file can fill up disk quite quickly.
