### ISSUE TITLE
How do I include the Postgres integration config files?

### ISSUE THREAD

**Issue by matthewcummings** [DataDog/heroku-buildpack-datadog#314]
Hello, I want to use your buildpack to pull metrics from Postgres but it does not seem to pick up my YAML file. I have a ./datadog directory in my app directory and I've tried adding my Postgres configs under it. I've tried a number of paths including ./datadog/conf.d/postgres.d/conf.yaml but my configs are not being acknowledged.

The only way I can get it to work is by copying (in the pre-run script) my Postgres yaml file into the ./apt/etc/datadog-agent directory, specifically under the postgres.d subdirectory but it's not clear that I am supposed to do that. Is that how it's supposed to work or should I be able to put it in ./datadog in the root of my app?

**Comment by arapulido** [comment]
Hello @matthewcummings  You should place them under `./datadog/conf.d/postgres.yaml`. 

I know this is a bit confusing. I will work on making this a bit more flexible and better documented.

**Comment by matthewcummings** [comment]
Hmm, I could swear that I tried that already. I'll try again, thank you @arapulido!

**Comment by matthewcummings** [comment]
OK, I see the line where the copy should happen https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L49

Not sure what's wrong. Anyway, I got it to work by copying the file into place in `prerun.sh` which is fine for now. . . I will try to figure out why the buildpack's copy is not working the intended way.

**Comment by forgingdestiny** [comment]
same thing - adding `cp "/app/datadog/postgres.yaml" "$DD_CONF_DIR/conf.d/postgres.d/conf.yaml"` worked for me in `prerun.sh`

**Comment by arapulido** [comment]
As there is now an [easier way to configure the Postgres integration](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#enabling-the-datadog-postgres-integration) I will close this issue

**Comment by jefferson-surge** [comment]
@arapulido unfortunately it's not clear to me from that link how I can set any of the other configuration values, such as the collection_interval. Will values still be pulled from app/datadog/postgres.yaml?

**Comment by arapulido** [comment]
@jefferson-surge If you need to define any of the other configuration values, then you will need to use `app/datadog/postgres.yaml` directly, without using `DD_ENABLE_HEROKU_POSTGRES`, which will always use the default values
