### ISSUE TITLE
Questions about "tcp connection error" during Heroku dyno releases

### ISSUE THREAD

**Issue by 29decibel** [DataDog/heroku-buildpack-datadog#326]
Hi Datadog team,

We recently experienced an outage (not necessarily caused by the agent) in our Heroku production after enabled Datadog agent using `heroku-buildpack-datadog`, the errors we were seeing in the Heroku logs are `tcp connection errors`, especially during dyno restarts.

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/97426/222472364-93a7c188-a17e-44c0-af32-b00a469a865a.png">

My question is does this normal to have lots of `tcp connection errors` during dyno restarts? In what way (if there is any chance) this could lead to H12 (timeout) errors which leads to outage? Thank you for any help or insights!

Some of other notes:
- We do successfully get lots of Datadog tracing and logs in our dashboard, so the agent configuration should be good
- When we are trying to mitigate the issue by remove the ENV variables from Heroku, the H12 errors count already start dropping, so it might not necessarily related to Datadog agent at all, but again those errors leads us to further investigation
- The Heroku H12 errors start when we are trying to enable Datadog RUM integration, however we don't think there is any relationship between RUM with Datadog agent, as the RUM directly connects metrics through JS, but it indeed will trigger a Heroku release

**Comment by arapulido** [comment]
Hello @29decibel This is definitely not normal, and something that we will need to have more information and probably have a look to your logs to try to debug this.

Can you open a support ticket, so we can safely look at your particular case, please?

I will close this issue, as there is not a lot more we can do here without more data.

**Comment by 29decibel** [comment]
Thank you @arapulido ! I opened one here https://help.datadoghq.com/hc/en-us/requests/1119708
