### ISSUE TITLE
`ENABLE_HEROKU_POSTGRES` (etc.) environment variables do not follow `DD_*` convention

### ISSUE THREAD

**Issue by nertzy** [DataDog/heroku-buildpack-datadog#332]
All of the environment variables that are used to configure the Datadog agent in this buildpack are prefixed with `DD_`, except for these:

* `ENABLE_HEROKU_POSTGRES`
* `POSTGRES_URL_VAR`
* `ENABLE_HEROKU_REDIS`
* `REDIS_URL_VAR`

This is unnecessarily confusing and a little bit risky, because these environment variables are also shared with the running application. I think it would be better if they were named something like:

* `DD_HEROKU_POSTGRES_ENABLED`
* `DD_HEROKU_POSTGRES_URL_VAR`
* `DD_HEROKU_REDIS_ENABLED`
* `DD_HEROKU_REDIS_URL_VAR`

That way, they are grouped together with other Datadog variables.

**Comment by arapulido** [comment]
Thanks for the feedback @nertzy . This has been now changed in the [latest release of the buildpack](https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/2.10).
