### ISSUE TITLE
Error from sed when setting a URL in DD_TAGS

### ISSUE THREAD

**Issue by tropictim** [DataDog/heroku-buildpack-datadog#343]
When setting a tag that has a URL in DD_TAGS, we're getting the following errors:
```
sed: -e expression #1, char 243: unknown option to `s'
sed: -e expression #1, char 220: unknown option to `s'
```

The tag still ends up getting set correctly despite the errors. The error appears to be happening [here](https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L305) and [here](https://github.com/DataDog/heroku-buildpack-datadog/blob/master/extra/datadog.sh#L307)

You can reproduce by setting DD_TAGS in `prerun.sh` to something like this: `git.repository_url:github.com/example/example`

**Comment by arapulido** [comment]
@tropictim thanks for reporting! I will have a look

**Comment by philipbjorge** [comment]
@arapulido -- 
It seems like after this buildpack upgrade our repository linking isn't working anymore?

![CleanShot 2023-08-31 at 11 23 31](https://github.com/DataDog/heroku-buildpack-datadog/assets/918891/22631f8a-d01a-456d-b879-d875c9c360e9)

![CleanShot 2023-08-31 at 11 24 57](https://github.com/DataDog/heroku-buildpack-datadog/assets/918891/8dcba8f2-2571-4c45-9032-7dc8d9e91985)
