### ISSUE TITLE
Repository URL regression

### ISSUE THREAD

**Issue by philipbjorge** [DataDog/heroku-buildpack-datadog#346]
We set the `git.repository_url:github.com/pachama/...` tag in our ENV to link our repository to traces.

Before today, this was working. After today, it is not.

Seems likely related to this change -- https://github.com/DataDog/heroku-buildpack-datadog/issues/343

![image](https://github.com/DataDog/heroku-buildpack-datadog/assets/918891/8fcbef51-e2c1-4c21-add0-ba1cae6b1d06)
![image](https://github.com/DataDog/heroku-buildpack-datadog/assets/918891/dd4acb78-fbb3-47c0-b349-195c6e284954)

**Comment by arapulido** [comment]
Hello @philipbjorge We had an issue before fixing #343 so you had to escape the url. Please, change your `repository_url` tags to avoid escaping forward slashes. (i.e. change to `github.com/pachama/...`). This is consistent with what other Datadog environments expects. I will update the release changelog to add a warning about this. 

Let me know if that fixes it for you. Thanks!

**Comment by arapulido** [comment]
hey @philipbjorge Actually, after a bit more testing, I see that in certain scenarios, we promote the backslashes to DD_TAGS, when conflicting with the YAML configuration.

I will prepare a release to fix this. 

Can you confirm that you are not backslashing your env variable? 

Thanks!

**Comment by arapulido** [comment]
Hello @philipbjorge Thanks again for reporting it so quickly. We have now push a fix for this (it fixes it for the test cases I have). Let me know if this works for you as well. Thanks!

**Comment by arapulido** [comment]
@philipbjorge hello! following up here. I just wanted to check that this was fixed for your use case. Thanks!

**Comment by philipbjorge** [comment]
@arapulido -- Thank you for following up, this looks like it's working perfectly. Thank you!
