### ISSUE TITLE
Support for new Logs feature

### ISSUE THREAD

**Issue by dmorgantini** [DataDog/heroku-buildpack-datadog#35]
Very exciting feature: https://www.datadoghq.com/blog/announcing-logs/

Doesn't look like this is currently supported in the buildpack.  Would be awesome if it was!

**Comment by jyee** [comment]
Thanks. This is a bit related to adding the ability to install agent integrations. Currently you should be able to enable the logging feature by setting the env var `DD_LOGS_ENABLED` to `true`, but you'll need a way to place your log configs into the datadog `conf.d` directory.

**Comment by quinn** [comment]
@jyee any updates and/or additional instructions on this? the instructions seem to assume that you would be able to modify the config yaml file which isn't possible with the buildpack, as far as I can see:

https://docs.datadoghq.com/logs/

Even if there is a conf.d dir that it's contents get mixed in, that would still mean that the slug would be modified outside of the app? this all seems kind of not really possible on heroku.

**Comment by quinn** [comment]
@jyee, for example, if I added something to my app's initialization that copied something into the conf.d dir, I would still need to restart the agent, and there doesn't seem to be a way to do that either.

**Comment by coffenbacher** [comment]
Hi @jyee any thoughts on this? My company is onboarding to Datadog and this is critical for us. I'm willing to dig into a forked buildpack and experiment, but if you have any pointers that would be helpful.

**Comment by jyee** [comment]
@coffenbacher We're working on it, but don't have an eta on release yet.

**Comment by coffenbacher** [comment]
Thanks for the update! Looking forward to it. My team will probably start using another service as an interim solution, and hopefully migrate to Datadog when this is ready.

**Comment by jeremy-lq** [comment]
Note: We have a feature request in for this. If interested you can open a ticket to be added to the card for tracking purposes. In the interim, you can ship your logs to a remote syslog drain, and then forward the logs from there using the Datadog Agent.

**Comment by rbright** [comment]
With the introduction of https://github.com/DataDog/heroku-buildpack-datadog/pull/49, should this now be usable? I'm curious if the issue I'm experiencing is due to misconfiguration or lack of support.

#### Environment

* Datadog Agent v6.3.2
* `DD_LOGS_ENABLED` set to `true`

#### datadog/conf.d/ruby.d/conf.yaml

```yaml
logs:
  - type: tcp
    port: 10518
    service: myservice
    source: ruby
```

I'm currently seeing the following error in the logs:

```
(start.go:226 in StartAgent) | Could not start logs-agent:  could not find any valid logs configuration
```

**Comment by rbright** [comment]
This appears to be working properly with a modification to the directory structure used in my setup.

Looking at https://github.com/DataDog/heroku-buildpack-datadog/commit/c8299dac666c977a6bc52d164b0d3e4363d9d72e, the script maps input YAML files in a manner that is inconsistent with the documented directory structure for Datadog configuration.

The script will perform the following mapping:

```
datadog/conf.d/ruby.yaml -> conf.d/ruby.d/conf.yaml
```

**Comment by num3a** [comment]
Did you succeed to display logs in the Log Management console ?

**Comment by mazondo** [comment]
@jeremy-lq We're about to dive into this - is official support possible now?

**Comment by jyee** [comment]
@mazondo Official support is still forthcoming, but will be available soon.

**Comment by mazondo** [comment]
Hypothetically, if one were wanting to be live with it within the next 3 weeks, and not holding you to anything...would you encourage that person to investigate alternatives?

**Comment by irabinovitch** [comment]
@mazondo The build pack here will still be relevant once the drain launches. The drain will only be responsible for forwarding application logs.  The build pack will still be required for complete monitoring.

**Comment by gaborszakacs** [comment]
Seems like the official Heroku logs drain is in public beta now. 🎉 
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/?tab=usregion#heroku-log-collection

**Comment by erikreedstrom** [comment]
@jyee The log drain seems to be ignoring the `-hostname` attribute from logplex, overwriting with the value`host`. Why does DD set this to `host` rather than use the value from logplex if the `&host=<some_name>` attribute isn't set on the drain?

**Comment by jeremy-lq** [comment]
@erikreedstrom `host` is a reserved attribute in Datadog Logs and cannot be remapped in a pipeline. You have a couple options:
* Use the host attribute in the https drain
* Send your logs in JSON and use `reserve attribute mapping` (https://docs.datadoghq.com/logs/processing/#edit-reserved-attributes)

While we do support RFC5424, the Heroku Syslog drain does not have the ability to prepend your API key so currently is not an option.

**Comment by erikreedstrom** [comment]
@jyee Thanks for quick response!

We definitely will look at mapping. We've opened DataDog/datadog-agent#3075 as well, as we think this will help us out in mapping the syslog procid (our instance hostname) to the correct host in the infrastructure map.

**Comment by bjeanes** [comment]
I fixed the hostname so that it maps to `dyno` (how I personally have this buildpack configured), by configuring the reserved attributes mapping to derive the hostname from `syslog.procid`, which has been filled with the Dyno on my side.

The default Heroku pipeline configured by DD when ingesting from logdrains sometimes sets the dyno to the wrong value (something like `heroku.<uuid>`).

This is actually because Heroku is inconsistent with the log lines they output. Some internal log lines use `source=<dyno> dyno=<internal id>` while others use `dyno=<dyno>`. The grok parse rules DD installs only parse expecting the second.

However, I added a remapper rule to rewrite `syslog.procid` to `dyno` and that restores some sanity. However, `dynotype` is not set as there doesn't seem to be a way to remap an attribute with any kind of transformation (grok parsing only applies to the log lines themselves, not already defined attributes)

**Comment by arapulido** [comment]
With the drain being publicly available (https://docs.datadoghq.com/logs/guide/collect-heroku-logs/?tab=ussite) and the new buildpack release fixing the agent log collector (https://github.com/DataDog/heroku-buildpack-datadog/releases/tag/1.14) to be able to send logs directly to Datadog from a log file if needed, I will mark this issue as resolved. 

For any specific issues people may be having with log collection, feel free to open a new issue describing your issue.

Thanks!
