### ISSUE TITLE
embedded/bin has at least one symlink broken

### ISSUE THREAD

**Issue by hubertlepicki** [DataDog/heroku-buildpack-datadog#350]
I am using this buildpack on Gigalixir, with https://github.com/gigalixir/gigalixir-buildpack-releases.git

What the gigalixir-buildpack-releases is doing is that it creates a tar file with an Elixir app release, along with the datadog Agent.

Since last night, we are getting this error, when the above buildpack executes:

```
remote:                
remote:        To list all commands:        
remote:                
remote:        _build/staging/rel/myapp_phoenix/bin/myapp_phoenix        
remote:                
remote: tar: ./.apt/opt/datadog-agent/embedded/bin/postmaster: File removed before we read it     
```

I think what is happening and what this error from GNU tar actually means, is that the "postmaster" file is a symlink that is broken.

I don't know if there are more broken symlinks, I haven't found a workaround just yet.

**Comment by arapulido** [comment]
Hello! Thanks for reporting!

I have created a branch that fixes this. Could you please try your build using this buildpack instead, please?

https://github.com/DataDog/heroku-buildpack-datadog.git#ara.pulido/broken_symlink

Once you confirm this fixes your issue, we will release a new version of the buildpack.

Thanks again!

**Comment by arapulido** [comment]
In the mean time, if anyone is experiencing the same issue, they can pin the previous agent version setting the variable `DD_AGENT_VERSION=7.47.0-1`

**Comment by arapulido** [comment]
@hubertlepicki Were you able to test the branch? Thanks!

**Comment by hubertlepicki** [comment]
@arapulido I'm sorry I wasn't. I will do today and get back

**Comment by arapulido** [comment]
@hubertlepicki Perfect, thanks for confirming, I will prepare a release.

**Comment by arapulido** [comment]
@hubertlepicki the new buildpack with the fix has been released. Thanks a lot for reporting!
