### ISSUE TITLE
Send Datadog event when Dyno starts

### ISSUE THREAD

**Issue by jyee** [DataDog/heroku-buildpack-datadog#36]
Generate an event in Datadog whenever a dyno host starts. Dyno names are reused, so it's a bit opaque when Heroku is shutting down or recycling hosts. This can lead to some misunderstandings about the state/performance of dynos. Sending events will allow for better insight.

**Comment by arapulido** [comment]
Closing, as it is an old issue, and we haven't seen a lot of demand here
