### ISSUE TITLE
Dyno tags seem to be wrong.

### ISSUE THREAD

**Issue by pwfff** [DataDog/heroku-buildpack-datadog#37]
I don't have any way to recreate this, but after installing this and running one web dyno with several worker dynos, all my stats are coming in tagged with web instead of worker (most of the time?). I've also seen the tags get stuck as a 'dyno:run.123' for a long period of time, even after the `heroku run` dyno is dead and gone.

I can see the dyno logs, so I know my celery tasks are running on the right machine. The tags are just coming in as a different dyno.

![image](https://user-images.githubusercontent.com/954340/38111115-64096d7c-3363-11e8-9535-fde04e39658f.png)

**Comment by jyee** [comment]
This might be related to another issue we've seen and it may be caused by how we're currently setting the hostname in dynos to be the app name. I'm currently working on a change to how hostname is handled. Would you be interested in helping to test that to see if it also resolves your issue?

**Comment by pwfff** [comment]
Certainly! I have some more time today to try and diagnose it myself as well.

**Comment by jyee** [comment]
@pwfff Try the `beta` branch of this repo:

```
heroku labs:enable runtime-dyno-metadata -a $(heroku apps:info|grep ===|cut -d' ' -f2)
heroku config:unset DD_HOSTNAME
heroku buildpacks remove https://github.com/DataDog/heroku-buildpack-datadog.git
heroku buildpacks:add --index 1 https://github.com/DataDog/heroku-buildpack-datadog.git#beta
```

Basically the above will enable Heroku lab's dyno metadata on your app, then unsets the hostname and installs the beta branch of the repo. The big difference is now we'll be tracking hosts. So rather than setting up your dashboards to think of host = app, you'll need to use the `appname` tag.

**Comment by pwfff** [comment]
Works great!

```
catullus:server pwf$ heroku labs:enable runtime-dyno-metadata -a my-app
Enabling runtime-dyno-metadata for my-app... done
catullus:server pwf$ heroku config:unset DD_HOSTNAME -a my-app
Unsetting DD_HOSTNAME and restarting ⬢ my-app... done, v272
 ▸    Release command executing: this config change will not be available until the command succeeds. Use `heroku releases:output` to view the log.
catullus:server pwf$ heroku buildpacks remove https://github.com/DataDog/heroku-buildpack-datadog.git -a my-app
 ▸    Unexpected arguments: remove, https://github.com/DataDog/heroku-buildpack-datadog.git
 ▸    See more help with --help
catullus:server pwf$ heroku buildpacks:remove https://github.com/DataDog/heroku-buildpack-datadog.git -a my-app
Buildpack removed. Next release on my-app will use:
  1. https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3
  2. heroku/python
  3. https://github.com/heroku/heroku-buildpack-pgbouncer
  4. https://github.com/dscout/wkhtmltopdf-buildpack.git
Run git push heroku master to create a new release using these buildpacks.
catullus:server pwf$ heroku buildpacks:add --index 1 https://github.com/DataDog/heroku-buildpack-datadog.git#beta -a my-app
Buildpack added. Next release on my-app will use:
  1. https://github.com/DataDog/heroku-buildpack-datadog.git#beta
  2. https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3
  3. heroku/python
  4. https://github.com/heroku/heroku-buildpack-pgbouncer
  5. https://github.com/dscout/wkhtmltopdf-buildpack.git
Run git push heroku master to create a new release using these buildpacks.
```

![image](https://user-images.githubusercontent.com/954340/38202813-b768a6f2-3662-11e8-8e74-d1ac20b11f50.png)

**Comment by jyee** [comment]
Thanks for the feeback! I have a couple other changes to finish and bundle up, but I'll include this change with the next versioned release.

**Comment by steakchaser** [comment]
Running the latest version of the buildpack + log drain.  dyno and dynotype always seem to be `web.1` and `web` respectively, despite have a worker dyno.  Is there something else I need to do to get the buildpack to detect the worker correctly?

**Comment by arapulido** [comment]
@steakchaser Can you open a new issue with your problem, please? Adding the version that you are running, and a bit more of description of the issue. Thanks!
