### ISSUE TITLE
Feature Request: Service tags for Heroku Postgres databases

### ISSUE THREAD

**Issue by nertzy** [DataDog/heroku-buildpack-datadog#370]
Thanks for the `DD_ENABLE_HEROKU_POSTGRES`, `DD_POSTGRES_URL_VAR`, and `DD_ENABLE_DBM` environment variables. With these, I can configure Datadog DBM tracing across a multitude of applications, including DBs that are dynamically provisioned. This is a great feature!

When I'm viewing my databases in the Datadog UI, they show up in a big list, with names like `ec2-nnn-nnn-nnn-nnn.compute-1.amazonaws.com` (where `nnn-nnn-nnn-nnn` is the IP address).

It's difficult to tell these DBs apart. It would be great if there were some way to add service tags or some other set of arbitrary key-values pairs to these DB instances. The documentation talks about how to do this via manual configuration, but I don't want to switch to that, as it will require more maintenance, losing the benefit of the env-var-based approach.

For example, if there were some way to tag with `#{application_name}-#{db_name}` e.g. `my-api-staging-GOLD` or similar, that would be very helpful.

**Comment by arapulido** [comment]
Hello @nertzy ! Thanks for the feature request. I have worked on a solution to this, and it is now available in a branch.

Would you be willing to test that branch to see if it works for your use case, please? [ara.pulido/db_tags](https://github.com/DataDog/heroku-buildpack-datadog/tree/ara.pulido/db_tags)

Documentation is available in the branch as well.

**Comment by jeffblake** [comment]
This is a great feature and will be appreciated, but in my opinion the number of ENV variables are getting a little out of control and confusing... I'd prefer to let us configure it in the datadog/conf.d/postgres.yaml. That way we don't have to reinvent the wheel. We could put placeholders in our conf for variables, such as `<DATABASE_URL>` and then the `datadog.sh` can swap in the values for us. That eliminates the need for extra env variables, and working with a standard conf file makes things easier to understand

**Comment by nertzy** [comment]
@jeffblake I agree, that's a great idea

**Comment by arapulido** [comment]
@jeffblake that's already available to do, if you use the `prerun.sh`. It would be very difficult to control what options would people like to change. If you need more flexibility, I indeed encourage to do just that. I will work on some documentation on how to do that

**Comment by arapulido** [comment]
@nertzy @jeffblake I have added the following documention: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#using-the-prerunsh-script-to-dynamically-change-the-integration-configuration

This would give you a lot more flexibility if needed, and we will keep the current env variables to ease the most basic use case
