### ISSUE TITLE
DD_DYNO_HOST option not useful for tracking multiple Heroku apps.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [DataDog/heroku-buildpack-datadog#40]
I really like the idea of the recently added `DD_DYNO_HOST` parameter and would love to use it, but we use Datadog to track a large application made up of many smaller Heroku apps, and since `DD_DYNO_HOST` uses the dyno name for the host value turning this on for all our apps would lead to really mangled metrics as multiple `web.1` hosts report very different metrics.

A more useful option for our use-case would be to use the app name + dyno name (so something like `my-app:web.1`, perhaps) as the host name, so that we can distinguish between dynos with the same name on different apps.

**Comment by jyee** [comment]
@undergroundwebdesigns Thanks. I had realized the problem with dyno name collisions and just pushed version 1.3.1 which uses appname.dynoname. Let me know how that works out for you.
