### ISSUE TITLE
Dynos appear twice in infrastructure list (appname.dynoname & dyno hostname)

### ISSUE THREAD

**Issue by jyee** [DataDog/heroku-buildpack-datadog#41]
There appears to be an issue when enabling the `DD_DYNO_HOST` setting causing dynos to appear in the infrastructure list twice. Once using the `appname.dynoname` format and a second time using the dyno host's name (guid). Metrics are associated with the dyno using the host's name, but not with the appname.dynoname.

This was reported to Datadog Support, but I've been unable to reproduce the issue. If you've seen this issue, please comment below so we can gather more data.

**Comment by jeremy-lq** [comment]
This was caused by hostnames not being RFC1123-compliant. Addressed by https://github.com/DataDog/heroku-buildpack-datadog/pull/42

**Comment by jyee** [comment]
This is now addressed and fixed in the 1.3.2 release.
