### ISSUE TITLE
Intermittent failures adding the GPG key from the ubuntu keyserver.

### ISSUE THREAD

**Issue by dreid** [DataDog/heroku-buildpack-datadog#50]
We occasionally see deployment failures related to adding the GPG key.

Restarting the build usually works but it's still annoying.

There are a few options for dealing with this:
1) Use a different keyserver (maybe the sks pool?)
2) Retry with the same keyserver.
3) Retry with a backup keyserver.
4) Embed the key. (This is my preference and what I did when I added GPG support to the unofficial datadog buildpack.)

```
-----> Install gpg key for Datadog APT Repository 
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.r0R7le26C8/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80/ A2923DFF56EDA6E76E55E492D3A80E30382E94DE
gpg: keyserver receive failed: No data
```

**Comment by philihp** [comment]
I would definitely switch to `pool.sks-keyservers.net`

**Comment by jyee** [comment]
I changed the key server to sks-keyservers, but I'm going to leave this open for a while. Should anyone else have issues with the key server reliability, I'm happy to consider adding retries or embedding the key.

**Comment by maxcountryman** [comment]
We ran into this today and it blocks deploys causing. We'll have to drop DataDog if there isn't a better solution to this.

**Comment by jyee** [comment]
Thanks for the reports about sks-keyservers. I think the best way forward is embedding the key.

**Comment by maxcountryman** [comment]
Embedding the key makes a lot of sense: we should never treat the network (any network) as reliable..!

**Comment by jyee** [comment]
Closing this, since the key is now included in the buildpack. I'll be cutting a new release shortly.
