### ISSUE TITLE
Agent is quite verbose

### ISSUE THREAD

**Issue by msiebuhr** [DataDog/heroku-buildpack-datadog#59]
We aggregate the Heroku drains to collect common metrics (the machine-ones are all but pointless to us; see #39).

But when checking the logs, we a debug-burp like this every ~10s:

```
2018-09-04T12:12:36.653264+00:00 app[web.1]: 2018-09-04 12:12:36 INFO (trace_writer.go:98) - flushed trace payload to the API, time:25.842345ms, size:5595 bytes
2018-09-04T12:12:41.673945+00:00 app[web.1]: 2018-09-04 12:12:41 INFO (stats_writer.go:266) - flushed stat payload to the API, time:45.72011ms, size:3091 bytes
```

This is especially annoying with interactive sessions (`heroku run bash --app foobar`).

Is there any way to turn this off?

**Comment by msiebuhr** [comment]
Looks like it can be shut up by

    heroku config:set LOG_LEVEL=WARN --app ...

Beware if your "real" app listens for LOG_LEVEL. (I would have loved for it to be `DD_LOG_LEVEL`).

Otherwise, here's a patch for the build-pack:
```diff
diff --git a/extra/datadog.sh b/extra/datadog.sh
index fd76b8c..bb1133a 100644
--- a/extra/datadog.sh
+++ b/extra/datadog.sh
@@ -60,6 +60,9 @@ sed -i "s/^#   - role:database$/#   - role:database\n$TAGS/" $DATADOG_CONF
 # Uncomment APM configs and add the log file location.
 sed -i -e"s|^# apm_config:$|apm_config:\n    log_file: $DD_APM_LOG|" $DATADOG_CONF

+# Quiet logs
+sed -i -e"s/^# log_level: INFO/log_level: WARN/"
+
 # For a list of env vars to override datadog.yaml, see:
 # https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config.go#L145
```

**Comment by drobert** [comment]
:+1: on using `DD_LOG_LEVEL`. Somewhat across the board in this buildpack existing heroku environment values are used and cannot be overridden (e.g. the application name is taken from the dyno with no ability to override). 

Especially for logging, though, it's important to be able to configure the datadog log levels without impacting my own application's logging. With heroku log drains, too, the log output actually costs companies money as some service is being paid to collect and store this 'noise'.

**Comment by technicalpickles** [comment]
I think this can be closed for https://github.com/DataDog/heroku-buildpack-datadog/issues/23 . It looks like `LOG_LEVEL` was renamed to `DD_LOG_LEVEL` at some point.
