### ISSUE TITLE
Incompatible with subdir plugin?

### ISSUE THREAD

**Issue by epot** [DataDog/heroku-buildpack-datadog#62]
My heroku deployment is failing if I try to add the datadog buildpack:

```
remote: -----> Installing Datadog runner
remote: -----> App not compatible with buildpack: https://github.com/negativetwelve/heroku-buildpack-subdir
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
``` 

Is there any workaround? 

App not compatible with buildpack: https://github.com/negativetwelve/heroku-buildpack-subdir

**Comment by jyee** [comment]
@epot  I'm not very familiar with the Subdir Buildpack or what use case it serves. Are you using the Subdir Buildpack to try to put the Datadog Buildpack into a subdir? Have you tried keeping it in the root dir (i.e. listing it in the `.buildpacks` file without a subdir specified)?

**Comment by epot** [comment]
I usually use it when mixing frameworks in the same repo, like npm (for the FE) and Play! (for the backend). It allows you to put the code in subfolders and have a clean structure.

**Comment by epot** [comment]
So no, I am not using it to do anything related to Datadog.

**Comment by arapulido** [comment]
@epot I think this is because that buildpack needs to be in index 1. We have added a warning to our documentation for this type of cases: https://github.com/DataDog/heroku-buildpack-datadog#installation Can you try that and see if it helps? Thanks!

**Comment by arapulido** [comment]
@epot where you able to try what I recommended above?

**Comment by epot** [comment]
Argl no sorry, but feel free to close this: I am not sure I'll have time in the near future. Worst case scenario I'll re-open it if what you suggest does not work. Thanks a lot for the pointer!

**Comment by arapulido** [comment]
No worries, @epot Thanks for following up. I will close it, but, of course, feel free to reopen if the suggestion doesn't work.
