### ISSUE TITLE
Edit apm_config in datadog.yaml

### ISSUE THREAD

**Issue by tylerb** [DataDog/heroku-buildpack-datadog#64]
I'm looking to enable APM Trace Search & Analytics. It requires that I add 

```
apm_config:
  analyzed_spans:
    app-name|http.request: 1
```

Is it possible for me to get this into `datadog.yaml` in the `apm_config` section somehow?

**Comment by jyee** [comment]
I've merged #82 which includes your work in #65. Thanks again for your contribution!
