### ISSUE TITLE
Add support for the Process Agent

### ISSUE THREAD

**Issue by abtreece** [DataDog/heroku-buildpack-datadog#66]
It would be nice to have the ability to enable the Datadog Process Agent on the instance. I have not found anything that references why this functionality is or isn't there.

something like `DD_PROCESS_AGENT_ENABLED=true` would add the config to datadog.yaml...

```
process_config:
    enabled: 'true'
    scrub_args: true
```

**Comment by yourbuddyconner** [comment]
According to the docs, it would appear that this feature ships natively with DataDog Agent v6+ and doesn't need to be started separately like the Trace Agent. However I'm also having a hard time getting the agents in my dynos to report process metrics as described by @abtreece, so I could be wrong...

**Comment by abtreece** [comment]
@yourbuddyconner the process functionality needs to be enabled via the referenced config parameters. I believe it should be as simple as adding them to the config that is deployed by the buildpack.

**Comment by yourbuddyconner** [comment]
I agree that it should be as easy as creating a `datadog.yaml` file in the `<project>/datadog` directory, but it doesn't appear that the buildpack is configured to use a file from that location: https://github.com/DataDog/heroku-buildpack-datadog/blob/50a95a89d25831b92c1211774c77ef6b25ad71e1/extra/datadog.sh#L22-L23

Am I reading that right you think?

**Comment by yourbuddyconner** [comment]
Just wonderful!

**Comment by abtreece** [comment]
Closing this issue as the PR which implements it has been merged
