### ISSUE TITLE
support DD_SERVICE_MAPPING at the agent level

### ISSUE THREAD

**Issue by drobert** [DataDog/heroku-buildpack-datadog#71]
The [java tracer](https://docs.datadoghq.com/tracing/setup/java/#configuration) supports a feature called "service mapping". When attempting a similar configuration in the ruby tracer, it was surprising to learn this is not a ubiquitous feature. That is, it's up to each tracer to implement this, which is awkward or difficult in polyglot environments.

It would be helpful, both to users of the agent as well as tracer writers, if service mapping were the responsibility of the agent, rather than the (or in addition to) the tracers, for consistent application. For example, if setting an environment variable `DD_SERVICE_MAPPING` to `foo:bar` would cause the agent to map, I could confidently apply this to both my ruby and java (and any other) environments.

**Comment by jyee** [comment]
@drobert I'm not too familiar with the Java tracer, but I think your idea is worth consideration by the Datadog APM team. Would you mind making a request on the Datadog trace agent repository: https://github.com/DataDog/datadog-trace-agent/issues?

This repository is just for the buildpack that installs the agents.
