### ISSUE TITLE
toggling for one-off dynos and 'release phase' work?

### ISSUE THREAD

**Issue by drobert** [DataDog/heroku-buildpack-datadog#72]
Because heroku applications are configured altogether (the same environment variables like `DISABLE_DATADOG_AGENT` are either on or off for *all* dynos within the application), there doesn't seem to be an obvious way to disable the agent for [one-off dynos](https://devcenter.heroku.com/articles/one-off-dynos), especially relevant for those of us using the [heroku scheduler](https://devcenter.heroku.com/articles/scheduler).

Secondarily, this is a similar question for the [heroku release phase](https://devcenter.heroku.com/articles/release-phase), e.g. when running database migrations post-deployment. Is there an easy way to disable datadog during this phase?

**Comment by jarcoal** [comment]
This is also a problem for us, and `heroku run` commands share this issue.

**Comment by jyee** [comment]
@drobert Thanks for your feedback. We've added a prerun script that you can use to disable the agent or perform other environment/configuration changes. Please take a look at the [updated README](https://github.com/DataDog/heroku-buildpack-datadog#prerun-script).
