### ISSUE TITLE
documentation and conf.d directions are misleading

### ISSUE THREAD

**Issue by drobert** [DataDog/heroku-buildpack-datadog#79]
Within the current README.md's "enabling integrations" section:

> You can enable Datadog Agent integrations by including an appropriately named YAML file inside a datadog/conf.d directory in the root of your application.
> 
> For example, to enable the PostgreSQL integration, create a file /datadog/conf.d/postgres.yaml in your application containing:

However in the very next section on "prerun", the configuration file used is `conf.d/postgres.d/conf.yaml` (as opposed to `conf.d/postgres.yaml` as indicated above).

It's my understanding that the buildpack must copy files from the directories' `conf.d/INTEGRATION.yaml` to the global `etc/conf.d/INTEGRATION.d/conf.yaml` file before prerun is executed, but this is not clear from the documentation. Such a note would be helpful.

**Comment by jyee** [comment]
@drobert Thanks for your feedback. You are correct that the prerun script runs after all of the integrations and other configurations are moved into place. I've made a small clarification to the readme that should help with this.
