### ISSUE TITLE
Buildpack bloats slug size disproportionately

### ISSUE THREAD

**Issue by drobert** [DataDog/heroku-buildpack-datadog#89]
IGiven the hard-coded uppert-bounds slug size of 500MB, and the datadog agent component of this is around 370MB (as evidenced by downloading a 'slug' (build) and running `du -hs` on .apt/opt/datadog-agent), it is unreasonable that the agent would occupy over half of our entire application space.

Looking more closely, almost 150MB of this image is the embedded/lib/python2.7 directory, which appears to be a full distribution of python plus required third-party libraries, including datadog's own.

Would it be at all possible to use heroku's own python 2.7 support for 'main python' and only include datadog-specific aspects in the buildpack?

**Comment by jyee** [comment]
@drobert We'll look into using the built-in Python.

However, you should be clear that the *compressed* limit for a slug is 500MB. The compressed size of the Datadog Agent is about 90MB (about 40MB of that is the compressed Python libraries), which is much less than half of your application space.

Slugs are uncompressed to become running Dynos and it's only at that time that the Agent would occupy 370MB. There is no published limit on the max size for a running Dyno.

**Comment by jodal** [comment]
Even though 90MB is only a fifth of the limit, most apps are not near the limit, so the size of the buildpack is still quite disproportionate to the rest of the slug.

A larger buildpack leads to longer transfer times, slower deploys, and slower scaling:

> Smaller slugs can be transferred to the dyno manager more quickly, allowing for more immediate scaling. You should try to keep your slugs as small and nimble as possible.

-- https://devcenter.heroku.com/articles/slug-compiler#slug-size

In our quest to reduce our slug size to get faster deploys, there's nothing else we can do that is even close to having the impact removing the DataDog buildpack would have.

**Comment by brentd** [comment]
We have a fairly large monolithic app, which without the Datadog agent is already past Heroku's 300MB soft cap, at 356MB. Heroku begins to warn you each deploy past 300MB.

Installing the Datadog agent buildpack brought our slug size to 486MB, which is close enough that we can't continue with it.

Has there been any progress using dependencies like Python already present in Heroku's stack?

**Comment by dlobue** [comment]
Another issue is it appears the buildpack installs the agent over the previous installation without cleaning the previous version up. This causes the slug to steadily get larger with ever agent update, eventually resulting in the slug exceeding Heroku's slug size limit.

I had to clear the build cache in order to get deploys working again. Clearing the cache brought our slug size from 519MB to 379MB.

I downloaded the new slug and slug of the last working build (which was 485MB compressed), and found a difference of 200MB between the datadog-agent install on the old slug vs the new one.

**Comment by arapulido** [comment]
Since this issue was opened, we have made some improvements in both the Agent and the buildpack to reduce its size.

If `DD_APM_ENABLED` is set to `false` because you are not using tracing, the tracing agent won't be included in the slug.

If `DD_PROCESS_AGENT` is not set to `true` because you are not using process monitoring, then the process agent won't be included in the slug.

You can read more about options that require recompiling the slug here: https://github.com/DataDog/heroku-buildpack-datadog#upgrading-and-slug-recompilation

Also, starting on Agent version 6.14, the size of the python binaries was reduced as well.

With all these improvements, we have the following approximated compressed sizes for the buildpack for agent versions 6.14 onwards:

* Without APM and without process agent: 71M
* With APM, without process agent: 81.5M
* With APM, with process agent: 91.1M

**Comment by arapulido** [comment]
I am closing this issue now based on the improvements we have made since it was first opened. Feel free to reopen or create a new one if it doesn't solve your issues

**Comment by jodal** [comment]
A reduction from 90 to 71 MB isn't going to cut it for us. I think the only proper solution here is to use Heroku's Python version instead of bundling your own.

**Comment by drobert** [comment]
> If DD_APM_ENABLED is set to false because you are not using tracing, the tracing agent won't be included in the slug.
> 
> If DD_PROCESS_AGENT is not set to true because you are not using process monitoring, then the process agent won't be included in the slug.

This doesn't make sense to me. Features being enabled or disabled are runtime concerns but the slug is a build-time concern. My team does not have a homogeneous setup for this across all dyno types in our heroku app. We have APM and tracing enabled in our `web` dynos but not in our backend dynos that process millions of messages.

**Comment by arapulido** [comment]
> > If DD_APM_ENABLED is set to false because you are not using tracing, the tracing agent won't be included in the slug.
> > If DD_PROCESS_AGENT is not set to true because you are not using process monitoring, then the process agent won't be included in the slug.
> 
> This doesn't make sense to me. Features being enabled or disabled are runtime concerns but the slug is a build-time concern. My team does not have a homogeneous setup for this across all dyno types in our heroku app. We have APM and tracing enabled in our `web` dynos but not in our backend dynos that process millions of messages.

This is not ideal, but it is a good way to reduce size of the slug if those features are not used, that's why it was implemented. In your case, the slug is built with APM enabled, and you can still not start it with that option in your worker dynos.

**Comment by jhubert** [comment]
> @drobert We'll look into using the built-in Python.

Have you had a chance to look into this? The slug size with Datadog is still huge and it's taken our slug over the 300mb warning limit.

**Comment by jaydorsey** [comment]
I have a similar concern with this as well. Would like to see this re-visited, because this is almost 25% (or more) of the slug limit.

**Comment by vineus** [comment]
Hey @arapulido ! We are also having this issue.

345MB for a sidekick service really seems like a lot (it's bigger than our deployed app).

We use the latest 7.25 version.

Could you re-open this ticket?

```
~ $ du -ha --max-depth 1 /app/.apt/opt/datadog-agent | sort -hr
345M    /app/.apt/opt/datadog-agent
249M    /app/.apt/opt/datadog-agent/embedded
96M     /app/.apt/opt/datadog-agent/bin
304K    /app/.apt/opt/datadog-agent/licenses
116K    /app/.apt/opt/datadog-agent/LICENSES
64K     /app/.apt/opt/datadog-agent/agent_requirements-py3.txt
16K     /app/.apt/opt/datadog-agent/version-manifest.json
8.0K    /app/.apt/opt/datadog-agent/version-manifest.txt
8.0K    /app/.apt/opt/datadog-agent/run
8.0K    /app/.apt/opt/datadog-agent/requirements-agent-release.txt
8.0K    /app/.apt/opt/datadog-agent/LICENSE
4.0K    /app/.apt/opt/datadog-agent/scripts
4.0K    /app/.apt/opt/datadog-agent/final_constraints-py3.txt
```

**Comment by arapulido** [comment]
Hello @vineus The agent embeds Python3.8, hence the side. but those 345MB are only the uncompressed ones. The biggest size of the agent compressed (the size that is taken into account for slug sizes) is 121MB. You can slim a bit the agent, disabling features that you don't use (i.e. if you don't use the process agent, or apm, as explained at: https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#optional-binaries

**Comment by DamienMetzger** [comment]
This is still an issue. I will be forced to stop using Datadog because I'm reaching the slug (hard) limit.

**Comment by arapulido** [comment]
@DamienMetzger can you open a support case to see your specific issue, please?

**Comment by akshay-birajdar** [comment]
We are a large monolithic application, and with the Datadog agent, we exceed the slug hard limit. This has become a blocker for us to use Datadog.
