### ISSUE TITLE
update the agent buildpack

### ISSUE THREAD

**Issue by palazzem** [DataDog/heroku-buildpack-datadog#9]
The current buildpack is not updated and it installs the deprecated `dd-trace-agent` binary. Now the Datadog Agent ships with the APM functionality, so we should update the code to get the latest agent version.

A user reported that because in a recent change, we've removed from our clients the deprecated port `7777` in favor of `8126`. See https://github.com/DataDog/dd-trace-rb/commit/3e6db23c26f7579095f38613414e3fc2696628da#commitcomment-21240986

**Comment by irabinovitch** [comment]
I believe @jyee  was looking into updating this.

**Comment by jyee** [comment]
Thanks, I've added a note for that on the Trello card: https://trello.com/c/jZ0Vl4de/1352-update-heroku-buildpack-for-5-12

**Comment by jyee** [comment]
I've updated master. It should now install the latest datadog agent (previously was installing all agent versions which caused some clobbering/overwriting of newer agents).
